%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Data\Acustics\Snakers4\Val\asr_calls_2_val.csv
%
% Auto-generated by MATLAB on 13-Jul-2022 18:00:08
clear
clc
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
% opts.DataLines = [7, 7];
opts.Delimiter = [",", "_"];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "val93314bbb530d04dtxt", "Var9"];
%opts.SelectedVariableNames = "val93314bbb530d04dtxt";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "val93314bbb530d04dtxt", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "val93314bbb530d04dtxt", "Var9"], "EmptyFieldRule", "auto");

% Import the data
asrcalls2val = readtable("D:\Data\Acustics\Snakers4\Val\asr_calls_2_val.csv", opts);


%% Clear temporary variables
clear opts
DirTR = "D:\Data\Acustics\Snakers4\";
fileWav = asrcalls2val.Var4(1);
file_name = (DirTR+replace(fileWav,'/','\'));

% FileRead = DirTR+fileWav;
% WavTR  = audioread(file_name);